Repository kubevirt/ipam-extensions, pull requests merged in 2024-06, with the labels that each got.

#22 ci: provide release manifests for user installation
  .github/workflows/publish-img.yaml
Labels: ci

#23 ci: allow github releases to write contents
  .github/workflows/publish-img.yaml
Labels: ci

#25 Fix GitHub release container img
  .github/workflows/publish-img.yaml
  Makefile
  dist/install.yaml
Labels: ci

#32 Add OWNERS file
  OWNERS
Labels: dco-signoff: yes, size/XS

#28 Transfer repo and rename to kubevirt-ipam-controller
  .github/workflows/checks.yaml
  .github/workflows/publish-img.yaml
  PROJECT
  README.md
  cmd/main.go
  config/certmanager/certificate.yaml
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/webhook/service.yaml
  dist/install.yaml
  go.mod
  pkg/ipamclaimswebhook/podmutator.go
  pkg/vmnetworkscontroller/controller.go
  test/e2e/e2e_suite_test.go
  test/e2e/persistentips_test.go
  test/go.mod
Labels: dco-signoff: yes, size/L, approved, lgtm

#33 cosmetics: Add new line
  test/e2e/persistentips_test.go
Labels: dco-signoff: yes, size/XS
