Repository kubevirt/ipam-extensions, pull requests merged in 2024-08, with the labels that each got.

#40 Fix Finalizer logic
  cmd/main.go
  pkg/claims/claims.go
  pkg/vminetworkscontroller/vmi_controller.go
  pkg/vminetworkscontroller/vmi_controller_test.go
  pkg/vmnetworkscontroller/vm_controller.go
  pkg/vmnetworkscontroller/vm_controller_test.go
  test/e2e/persistentips_test.go
  test/env/matcher.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#56 git actions: Free storage
  .github/workflows/checks.yaml
Labels: size/S, dco-signoff: yes, approved, lgtm

#54 Add missing rbacs
  config/rbac/role.yaml
  dist/install.yaml
Labels: size/S, dco-signoff: yes, approved, lgtm

#52 Cache minimal data
  cmd/main.go
Labels: size/S, dco-signoff: yes, approved, lgtm

#53 ci: add a pull request template
  .github/pull_request_template.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#57 e2e: Collect git action data in case of a failure
  .github/workflows/checks.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/persistentips_test.go
Labels: dco-signoff: yes, approved, lgtm, size/M
