Repository kubevirt/ipam-extensions, pull requests merged in 2024-12, with the labels that each got.

#80 Set the GitHub runner image to Ubuntu 22.04 explicitly.
  .github/workflows/checks.yaml
  .github/workflows/publish-img.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#77 template: specify priority class
  config/manager/manager.yaml
  dist/install.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#79 README: Remove usage of deprecated .spec.running field
  README.md
Labels: dco-signoff: yes, approved, lgtm, size/XS

#73 UDN: Use managedTap instead passt
  test/e2e/persistentips_test.go
Labels: size/S, dco-signoff: yes, approved, lgtm

#82 Remove non-existent package msbuild in latest ubuntu images
  .github/workflows/checks.yaml
  .github/workflows/publish-img.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#75 e2e, persistent-ip: Unify primary,secondary tests (primary UDNs use managedTap)
  test/e2e/persistentips_test.go
  test/env/getter.go
  test/env/matcher.go
Labels: dco-signoff: yes, size/L, approved, lgtm
