Repository kubevirt/ipam-extensions, pull requests merged in 2024-09, with the labels that each got.

#60 Allow setting custom KUBECONFIG
  Makefile
  hack/cluster.sh
Labels: dco-signoff: yes, approved, lgtm, size/XS

#62 cluster-sync: Use rollout instead of wait
  hack/cluster.sh
Labels: dco-signoff: yes, approved, lgtm, size/XS

#36 Support primary network
  pkg/claims/claims.go
  pkg/config/types.go
  pkg/ipamclaimswebhook/podmutator.go
  pkg/ipamclaimswebhook/podmutator_test.go
  pkg/udn/primary_network.go
  pkg/vminetworkscontroller/vmi_controller.go
  pkg/vminetworkscontroller/vmi_controller_test.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#64 udn: rename the annotation used
  pkg/config/types.go
  pkg/ipamclaimswebhook/podmutator_test.go
Labels: dco-signoff: yes, approved, lgtm, size/XS

#66 e2e: Fix artifacts collecting
  .github/workflows/checks.yaml
  .gitignore
  test/e2e/e2e_suite_test.go
Labels: dco-signoff: yes, size/XS

#67 udpn: Add missing error wrapping
  pkg/udn/primary_network.go
  pkg/vminetworkscontroller/vmi_controller_test.go
Labels: dco-signoff: yes, approved, lgtm, size/XS

#68 cluster: Use --opt-out-kv-ipam
  hack/cluster.sh
Labels: dco-signoff: yes, size/XS

#70 pod mutator, unit tests: Fix flaky test
  pkg/ipamclaimswebhook/podmutator_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm
