Repository kubevirt/ipam-extensions, pull requests merged in 2025-07, with the labels that each got.

#108 [release-0.2.1] claims: Format key to domain name
  .github/workflows/checks.yaml
  .github/workflows/publish-img.yaml
  Makefile
  pkg/claims/claims.go
  pkg/vminetworkscontroller/vmi_controller_test.go
  pkg/vmnetworkscontroller/vm_controller_test.go
  test/e2e/persistentips_test.go
Labels: dco-signoff: yes, size/M

#114 [release-0.2.4] feat: use branch name for image tagging with improved workflow logic
  .github/workflows/checks.yaml
  .github/workflows/publish-img.yaml
  Makefile
  config/manager/kustomization.yaml
  dist/install.yaml
  hack/sanitize-branch.sh
Labels: dco-signoff: yes, approved, lgtm, size/M

#115 [releas-0.2.1] feat: use branch name for image tagging with improved workflow logic
  .github/workflows/checks.yaml
  .github/workflows/publish-img.yaml
  Makefile
  config/manager/kustomization.yaml
  dist/install.yaml
  hack/sanitize-branch.sh
Labels: dco-signoff: yes, approved, lgtm, size/M

#105 udn, static ips, webhook: use multus default network annotation to specify MAC and IP addresses for KubeVirt VMs
  Makefile
  cmd/main.go
  go.mod
  go.sum
  hack/cluster.sh
  pkg/config/types.go
  pkg/ipamclaimswebhook/podmutator.go
  pkg/ipamclaimswebhook/podmutator_test.go
  pkg/ips/families.go
  pkg/ips/families_test.go
  pkg/ips/primarynetwork.go
  pkg/ips/primarynetwork_test.go
  test/e2e/persistentips_test.go
  test/env/generate.go
  test/env/matcher.go
  vendor/github.com/k8snetworkplumbingwg/ipamclaims/pkg/crd/ipamclaims/v1alpha1/types.go
  vendor/github.com/k8snetworkplumbingwg/ipamclaims/pkg/crd/ipamclaims/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/api/resource/v1alpha3/generated.proto
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1beta1/generated.proto
  vendor/k8s.io/api/resource/v1beta1/types.go
  vendor/k8s.io/api/resource/v1beta1/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: dco-signoff: yes, approved, lgtm, size/XXL
