Repository kubevirt/ipam-extensions, pull requests merged in 2025-05, with the labels that each got.

#100 Set container's TerminationMessagePolicy to FallbackToLogsOnError
  config/manager/manager.yaml
  dist/install.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#101 Add Network policies
  config/default/kustomization.yaml
  config/networkpolicy/allow-egress-dns.yaml
  config/networkpolicy/allow-egress-kube-apiserver.yaml
  config/networkpolicy/allow-ingress-to-service.yaml
  config/networkpolicy/kustomization.yaml
  dist/install.yaml
  hack/cluster.sh
  hack/install-deny-all-net-pol.sh
Labels: dco-signoff: yes, size/L, approved, lgtm

#102 readme: Add ref for cert-manager installation
  README.md
Labels: dco-signoff: yes, approved, lgtm, size/XS

#103 claims: Format key to domain name
  Makefile
  pkg/claims/claims.go
  pkg/vminetworkscontroller/vmi_controller_test.go
  pkg/vmnetworkscontroller/vm_controller_test.go
  test/e2e/persistentips_test.go
Labels: dco-signoff: yes, approved, lgtm, size/M
